### ISSUE TITLE
Question: What is the purpose of @Autobind vue3-oop decorator ?

### ISSUE THREAD

**Issue by rdhainaut** [agileago/vue3-oop#2]
In the example show on the readme (from home page of this project), I don't understand why we should use the @Autobind decorator ? I have try to understand the doc website https://agileago.github.io/vue3-oop/ but i have not really understand the usage of this decorator ?

```
 @Mut() count = 1

  add() {
    this.count++
  }

  @Autobind() // Why use Autobind on remove method and on remove method only ?
  remove() {
    this.count--
  }

```

**Comment by agileago** [comment]
see this.  https://github.com/andreypopp/autobind-decorator
