### ISSUE TITLE
Question: How to set default value for props ?

### ISSUE THREAD

**Issue by rdhainaut** [agileago/vue3-oop#3]
Can you please give an exemple with default value for props ?
Thanks you

**Comment by agileago** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/11799110/160229342-76e8e11e-643e-4a9d-a3c2-dce9ed14550b.png">
 and in ide you will see

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/11799110/160229373-027f47a1-f6d2-4deb-9359-d65e9fb52bd9.png">
