### ISSUE TITLE
Question: What means "@Mut" decorator and is it works with object too ?

### ISSUE THREAD

**Issue by rdhainaut** [agileago/vue3-oop#4]
First question: @Mut decorator can it works with object value ? 
for exemple:
```
@Mut()
items: {label: string, value: number}[];

InitItems() {
  this.item.push({label: 'vue', value: 1});
}
```

Second question: What means "Mut" ?
Is it the abreviation of mute or mutation or ... ? 
Sorry to say that but the name is not explicite. 
If i understand well is the equivalent of "ref" from composition api (or reactive).
Maybe @Ref or @Reactive would be more explicite.
Warning: @Ref word could be ambigus.

What is your opinion about this ?

**Comment by agileago** [comment]
##  first

of couse it works object. by the way. it works any data type

## second

it is **mutable** ,  and it Inspired by rust.  https://doc.rust-lang.org/std/keyword.mut.html

it use `ref` in the hood. i just want you to forget **ref and reactive**
