### ISSUE TITLE
vue3创建的项目 会报错

### ISSUE THREAD

**Issue by djkloop** [agileago/vue3-oop#9]
## 直接用官方的vue命令创建后安装库报错
```
error message: Uncaught ReferenceError: exports is not defined
```
## 报错截图
![image](https://user-images.githubusercontent.com/21050914/218257913-7b05c628-8386-4815-95df-dfd08a08fa83.png)
![image](https://user-images.githubusercontent.com/21050914/218257924-9e10ecca-3ba3-40fa-a1f7-065add2e4aca.png)
```
issus demo -> https://github.com/djkloop/vue3-oop-vite-error
```

**Comment by agileago** [comment]
tsconfig有问题   用这个   https://github.com/agileago/fe-template/blob/master/tsconfig.json

**Comment by agileago** [comment]
目前 jsx 插件还不支持 ts project referrence

**Comment by agileago** [comment]
目前建议只用tsx

**Comment by djkloop** [comment]
已解决  @agileago

**Comment by agileago** [comment]
咋突然用oop了？
